package com.nurdinaffandidev.quiz_service.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Entity representing a Question in the quiz system.
 * Contains question details such as category, difficulty,
 * possible options, question text, and correct answer.
 */
@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Question {
    // Primary key for Question entity, auto-generated by the database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    // Category of the question (e.g., Java, Math)
    private String category;

    // Difficulty level of the question (e.g., Easy, Medium, Hard)
    private String difficulty;

    // First answer option
    private String option1;

    // Second answer option
    private String option2;

    // Third answer option
    private String option3;

    // Fourth answer option
    private String option4;

    // The actual question text/title
    private String questionTitle;

    // The correct answer to the question
    private String correctAnswer;
}
